version: '3'
services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: react/
    ports:
     - "3000:3000"
  python:
    build:
      dockerfile: docker/Dockerfile
      context: python/
    volumes:
      - ./python:/opt/retipy
    ports:
     - "5000:5000"
  backend:
    build:
      context: rest/
      dockerfile: docker/Dockerfile
      args:
        backendUrl: http://python:5000/retipy
    ports:
      - "8080:8080"
    links:
      - python
